# Site settings
title: Convergence | A UCC Student Publication
email: your-email@domain.com
description: >
  Convergence is the oldest student-led publication in Canada. Written by students at Upper Canada College, Convergence aims to examine the world, whether it be on a school level, international level, and anything in between.
baseurl: "/convergence" # the subpath of your site, e.g. /blog
url: "http://matthewwang.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
